import { ItemView, WorkspaceLeaf } from 'obsidian';
import D20DicePlugin from './main';
export declare const CHAT_VIEW_TYPE = "dice-chat-view";
export declare class DiceChatView extends ItemView {
    private plugin;
    private apiClient;
    private chatContainer;
    private messageInput;
    private diceSelectionContainer;
    private expressionDisplay;
    private rollButton;
    private diceExpression;
    private diceCounts;
    private modifier;
    private userRole;
    private username;
    private isPolling;
    private pollTimeout;
    private lastMessageId;
    isConnected: boolean;
    constructor(leaf: WorkspaceLeaf, plugin: D20DicePlugin);
    getViewType(): string;
    getDisplayText(): string;
    getIcon(): string;
    onOpen(): Promise<void>;
    private showAuthenticationSetup;
    private showUserSetup;
    private setupChatInterface;
    private setupDMDiceControls;
    private updateDiceDisplay;
    private clearDice;
    private sendChatMessage;
    private sendDiceRequest;
    private rollDice;
    private loadMessages;
    private displayMessages;
    private populateDiceFromRequest;
    private startPolling;
    private stopPolling;
    private disconnect;
    private logout;
    private handleApiError;
    onClose(): Promise<void>;
}
