import { Plugin } from 'obsidian';
import { DiceSettings } from './settings';
export default class D20DicePlugin extends Plugin {
    settings: DiceSettings;
    private diceOverlay;
    private dice;
    private isVisible;
    private controlsPanel;
    private isDraggingControls;
    private controlsDragOffset;
    private clickthroughState;
    private updateClickthroughCallback;
    private updateRollButtonTextCallback;
    private updateDiceCountDisplayCallback;
    private chatRibbonIcon;
    onload(): Promise<void>;
    onunload(): Promise<void>;
    private toggleDiceOverlay;
    private showDiceOverlay;
    private setupControlsDragging;
    private showResult;
    private updateOverlaySize;
    private hideDiceOverlay;
    loadSettings(): Promise<void>;
    saveSettings(): Promise<void>;
    refreshDiceView(): void;
    toggleClickthrough(): void;
    refreshApiIntegration(): void;
    openChatView(): Promise<void>;
    handleDiceRequest(expression: string, description: string): void;
    private parseDiceExpression;
    private handleRollComplete;
    private updateDiceStatusDisplay;
}
